# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_sample
#'
#' @description Rcpp sample function
#'
#' @param x Vector of elements to sample from.
#' @param n Integer with size of the sample.
#' @param replace Logical if sample with replacement.
#'
#' @details
#' \code{Rcpp} implementation of the \code{sample} function.
#'
#' @seealso
#' \code{\link{sample}}
#'
#' @return vector
#'
#' @keywords internal
#'
#' @name rcpp_sample
#' @export
rcpp_sample <- function(x, n, replace = FALSE) {
    .Call(`_shar_rcpp_sample`, x, n, replace)
}

